FROM php:8.2

COPY ./docker/php/php.ini /usr/local/etc/php/

RUN apt-get update \
  && apt-get install -y zlib1g-dev curl vim libzip-dev libc-client-dev libkrb5-dev \
  && docker-php-ext-install zip pdo_mysql

#Composer install
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer